http.host: "0.0.0.0"
node.name: logstash
path.config: /usr/share/logstash/pipeline

xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.username: logstash_system
xpack.monitoring.elasticsearch.password: 'logstash_system-password-here'
xpack.monitoring.elasticsearch.hosts: [ 'https://es01:9200' ]
xpack.monitoring.elasticsearch.ssl.certificate_authority: /usr/share/elasticsearch/config/certificates/ca/ca.crt
