version: "3"
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    container_name: es01
    ports:
      - "9200:9200"
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xmx1g -Xms1g"
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    networks:
      - elk

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    container_name: es02
    ports:
      - "9201:9200"
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xmx1g -Xms1g"
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - elk

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    container_name: es03
    ports:
      - "9202:9200"
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xmx1g -Xms1g"
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:${ELK_VERSION}
    container_name: logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
    environment:
      - "ES_JAVA_OPTS=-Xmx1g -Xms1g"
    ports:
      - "5000:5000"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
    container_name: kibana
    ports:
      - "5601:5601"
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - elk

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - "./nginx/etc/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/public:/usr/share/nginx/html:ro"
      - "./nginx/etc/.htpasswd.user:/etc/nginx/.htpasswd.user:ro"
    links:
      - es01
      - es02
      - es03
      - kibana
    depends_on:
      - es01
      - es02
      - es03
      - kibana
    ports:
      - "80:80"
    networks:
      - elk

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elk:
    driver: bridge
